export const COPILOT_REPORT_CATALOG = [
  {
    key: 'leads_pipeline',
    name: 'Leads Pipeline',
    permission: 'Leads Pipeline',
    path: '/reports/sales/pipeline',
    filters: ['date_from', 'date_to', 'assigned_to', 'stage'],
  },
  {
    key: 'sales_activities',
    name: 'Sales Activities',
    permission: 'Sales Activities',
    path: '/reports/sales/activities',
    filters: ['date_from', 'date_to', 'assigned_to'],
  },
  {
    // Keep in sync with api/app/Services/AiCopilot/AiSystemCatalog.php
    key: 'sales_to_telesales',
    name: 'Leads To Telesales',
    permission: 'Leads Pipeline',
    path: '/reports/sales/to-telesales',
    filters: ['date_from', 'date_to'],
    requiresModule: 'telesales',
  },
  {
    key: 'meetings',
    name: 'Meetings Report',
    permission: 'Meetings Report',
    path: '/reports/sales/meetings',
    filters: ['date_from', 'date_to', 'assigned_to'],
  },
  {
    key: 'reservations',
    name: 'Reservations Report',
    permission: 'Reservations Report',
    path: '/reports/sales/reservations',
    filters: ['date_from', 'date_to', 'assigned_to'],
  },
  {
    key: 'closed_deals',
    name: 'Closed Deals',
    permission: 'Closed Deals',
    path: '/reports/sales/closed-deals',
    filters: ['date_from', 'date_to', 'assigned_to'],
  },
  {
    key: 'cancellation',
    name: 'Cancellation Report',
    permission: 'Cancellation Report',
    path: '/reports/sales/cancellation',
    filters: ['date_from', 'date_to', 'assigned_to'],
  },
  {
    key: 'rent',
    name: 'Rent Report',
    permission: 'Rent Report',
    path: '/reports/sales/rent',
    filters: ['date_from', 'date_to', 'assigned_to'],
  },
  {
    key: 'proposals',
    name: 'Proposals Report',
    permission: 'Proposals Report',
    path: '/reports/sales/proposals',
    filters: ['date_from', 'date_to', 'assigned_to'],
  },
  {
    key: 'check_in',
    name: 'Check In Report',
    permission: 'Check In Report',
    path: '/reports/sales/check-in',
    filters: ['date_from', 'date_to', 'assigned_to'],
  },
    {
    key: 'customers',
    name: 'Customers Report',
    permission: 'Customers Report',
    path: '/reports/sales/customers',
    filters: ['date_from', 'date_to'],
    requiresCompanyType: 'general',
  },
  {
    key: 'targets_revenue',
    name: 'Targets & Revenue',
    permission: 'Targets & Revenue',
    path: '/reports/sales/revenue',
    filters: ['date_from', 'date_to'],
  },
  {
    key: 'imports',
    name: 'Imports Report',
    permission: 'Imports Report',
    path: '/reports/sales/imports',
    filters: ['date_from', 'date_to'],
  },
  {
    key: 'exports',
    name: 'Exports Report',
    permission: 'Exports Report',
    path: '/reports/sales/exports',
    filters: ['date_from', 'date_to'],
  },
]
