export const ROLES = [
  'Director',
  'Operation Manager',
  'Sales Admin',
  'Branch Manager',
  'Sales Manager',
  'Team Leader',
  'Sales Person',
  'Telesales Manager',
  'Telesales Team Leader',
  'Telesales Agent',
  'Customer Manager',
  'Customer Team Leader',
  'Customer Agent',
  'Marketing Manager',
  'Marketing Moderator',
  'Support Manager',
  'Support Team Leader',
  'Support Agent',
  'Accountant',
  'Custom',
];

export const STATUSES = ['Active', 'Inactive', 'Suspended'];

export const ROLE_HIERARCHY = {
  'Branch Manager': ['Sales Admin'],
  'Sales Manager': ['Sales Admin', 'Branch Manager'],
  'Team Leader': ['Sales Manager', 'Branch Manager', 'Sales Admin'],
  'Sales Person': ['Team Leader', 'Sales Manager', 'Branch Manager', 'Sales Admin', 'Operation Manager'],
  'Telesales Manager': ['Sales Admin', 'Branch Manager', 'Director', 'Operation Manager'],
  'Telesales Team Leader': ['Telesales Manager', 'Sales Admin', 'Branch Manager', 'Director', 'Operation Manager'],
  'Telesales Agent': ['Telesales Team Leader', 'Telesales Manager', 'Sales Admin', 'Branch Manager', 'Director', 'Operation Manager'],
  'Customer Team Leader': ['Customer Manager', 'Sales Admin'],
  'Customer Agent': ['Customer Team Leader', 'Customer Manager', 'Sales Admin'],
  'Customer Manager': ['Sales Admin', 'Branch Manager', 'Director'],
  'Marketing Manager': ['Director', 'Operation Manager'],
  'Marketing Moderator': ['Marketing Manager'],
  'Support Team Leader': ['Support Manager'],
  'Support Agent': ['Support Team Leader', 'Support Manager'],
};

export const PERMISSIONS = {
  Leads: ['addLead', 'showCreator', 'editInfo', 'editPhone', 'importLeads', 'exportLeads', 'viewDuplicateLeads', 'actOnDuplicateLeads', 'addAction', 'receiveLeads'],
  Inventory: [
    'addCategory',
    'addItems',
    'addProject',
    'addProperties',
    'viewAllProperties',
    'exportProject',
    'exportProperties',
    'exportCategory',
    'exportItem',
    'revertSoldProperty',
    'deleteInventory',
    'addBroker',
    'addDeveloper',
    'showRequests',
  ],
  Marketing: ['showMarketingDashboard', 'showCampaign', 'addLandingPage', 'integration'],
  Telesales: ['showModule', 'addLead', 'importLeads', 'editLead', 'deleteLead', 'assignLead', 'receiveLeads', 'transferToSales', 'viewDashboard', 'viewReports', 'viewHistoricalRecords', 'viewDuplicateLeads', 'bulkTransferToSales', 'export'],
  Customers: ['showModule', 'convertFromLead', 'addCustomer', 'editInfo', 'deleteCustomer'],
  ContractCollections: ['showModule', 'viewContracts', 'viewInstallments', 'payInstallment', 'printReceipt', 'exportReports'],
  Control: [
    'addRegions',
    'addArea',
    'addStage',
    'addSource',
    'userManagement',
    'addUsers',
    'editUsers',
    'toggleUsers',
    'changeUserPassword',
    'deleteUsers',
    'multiAction',
    'salesComment',
    'allowActionOnTeam',
    'assignLeads',
    'checkInOutApprovals',
    'showReports',
    'editConfigurationSettings',
    'addInputs',
    'addDepartment',
  ],
};

export const REPORT_MODULES = [
  'Leads Pipeline',
  'Sales Activities',
  'Meetings Report',
  'Reservations Report',
  'Cancellation Report',
  'Closed Deals',
  'Rent Report',
  'Proposals Report',
  'Check In Report',
  'Customers Report',
  'Targets & Revenue',
  'Imports Report',
  'Exports Report',
];

export const PERM_LABELS_AR = {
  groups: {
    Leads: 'الليدز',
    Inventory: 'المخزون',
    Marketing: 'التسويق',
    Telesales: 'التيليسيلز',
    Customers: 'العملاء',
    Support: 'الدعم',
    Control: 'التحكم',
    Reports: 'التقارير',
  },
  report_modules: {
    'Leads Pipeline': 'بايبلاين الليدز',
    'Sales Activities': 'نشاطات المبيعات',
    'Meetings Report': 'تقرير الاجتماعات',
    'Reservations Report': 'تقرير الحجوزات',
    'Closed Deals': 'الصفقات المغلقة',
    'Rent Report': 'تقرير الإيجارات',
    'Proposals Report': 'تقرير العروض',
    'Check In Report': 'تقرير تسجيل الدخول',
    'Customers Report': 'تقرير العملاء',
    'Targets & Revenue': 'الأهداف والإيرادات',
    'Imports Report': 'تقرير الاستيراد',
    'Exports Report': 'تقرير التصدير',
  },
  actions: {
    view: 'عرض',
    create: 'إنشاء',
    assign: 'تعيين',
    addLead: 'إضافة ليد',
    addInputs: 'إضافة إدخالات',
    showCreator: 'عرض المنشئ',
    editPhone: 'تعديل الهاتف',
    showCampaigns: 'عرض الحملات',
    addLandingPages: 'إضافة صفحات هبوط',
    integrations: 'التكاملات',
    exportReports: 'تصدير التقارير',
    showReports: 'عرض التقارير',
    showCustomerModule: 'عرض موديول العملاء',
    convertLeadToCustomer: 'تحويل ليد إلى عميل',
    addNewCustomer: 'إضافة عميل جديد',
    convertFromLead: 'تحويل من ليد',
    addCustomer: 'إضافة عميل',
    editInfo: 'تعديل البيانات',
    deleteCustomer: 'حذف العميل',
    showModule: 'عرض الموديول',
    addTickets: 'إضافة تذاكر',
    sla: 'اتفاقية مستوى الخدمة',
    convertFromCustomer: 'تحويل من عميل',
    reports: 'التقارير',
    deleteTickets: 'حذف التذاكر',
    addRegions: 'إضافة مناطق',
    addArea: 'إضافة منطقة',
    addStage: 'إضافة مرحلة',
    addSource: 'إضافة مصدر',
    userManagement: 'إدارة المستخدمين',
    multiAction: 'أكشنات متعددة',
    salesComment: 'تعليق مبيعات',
    allowActionOnTeam: 'السماح بالأكشن على الفريق',
    assignLeads: 'تعيين ليدز',
    checkInOutApprovals: 'موافقات الحضور والانصراف',
    importLeads: 'استيراد ليدز',
    exportLeads: 'تصدير ليدز',
    viewDuplicateLeads: 'عرض الليدز المكررة',
    actOnDuplicateLeads: 'اتخاذ إجراء على الليدز المكررة',
    addAction: 'إضافة إجراء على الليد',
    receiveLeads: 'استلام الليدز',
    export: 'تصدير',
    addDepartment: 'إضافة قسم',
    addUsers: 'إضافة مستخدمين',
    editUsers: 'تعديل المستخدمين',
    toggleUsers: 'تفعيل/إيقاف المستخدمين',
    changeUserPassword: 'تغيير كلمة مرور المستخدم',
    deleteUsers: 'حذف المستخدمين',
    editConfigurationSettings: 'تعديل إعدادات الكونفيجوريشن',
    addProducts: 'إضافة منتجات',
    addCategory: 'إضافة تصنيف',
    addItems: 'إضافة عناصر',
    addProject: 'إضافة مشروع',
    addUnits: 'إضافة وحدات',
    addProperties: 'إضافة عقارات',
    viewAllProperties: 'عرض كل الوحدات',
    exportProject: 'تصدير المشاريع',
    exportProperties: 'تصدير العقارات',
    exportCategory: 'تصدير التصنيفات',
    exportItem: 'تصدير العناصر',
    revertSoldProperty: 'إرجاع وحدة Sold إلى Available',
    addBroker: 'إضافة وسيط',
    addDeveloper: 'إضافة مطور',
    showRequests: 'عرض الطلبات',
    deleteInventory: 'حذف بيانات المخزون',
    showMarketingDashboard: 'عرض لوحة التسويق',
    showCampaign: 'عرض الحملة',
    addLandingPage: 'إضافة صفحة هبوط',
    integration: 'التكامل',
  },
};

export const getPermissionDisplayLabel = (group, permissionKey, isArabic = false) => {
  if (group === 'Leads' && permissionKey === 'receiveLeads') {
    return isArabic ? 'استلام الليدز المحولة من التليسيلز' : 'Receive Converted Telesales Leads';
  }

  if (group === 'Inventory' && permissionKey === 'deleteInventory') {
    return isArabic ? 'حذف سجلات المخزون' : 'Delete Inventory Records';
  }

  if (isArabic && PERM_LABELS_AR.actions && PERM_LABELS_AR.actions[permissionKey]) {
    return PERM_LABELS_AR.actions[permissionKey];
  }

  const withSpaces = String(permissionKey || '')
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .trim();

  return withSpaces.charAt(0).toUpperCase() + withSpaces.slice(1);
};
