const COUNTRY_DIAL_CODE_MAP = {
  AD: '376',
  AE: '971',
  AF: '93',
  AG: '+1-268',
  AI: '+1-264',
  AL: '355',
  AM: '374',
  AO: '244',
  AQ: '',
  AR: '54',
  AS: '+1-684',
  AT: '43',
  AU: '61',
  AW: '297',
  AX: '+358-18',
  AZ: '994',
  BA: '387',
  BB: '+1-246',
  BD: '880',
  BE: '32',
  BF: '226',
  BG: '359',
  BH: '973',
  BI: '257',
  BJ: '229',
  BL: '590',
  BM: '+1-441',
  BN: '673',
  BO: '591',
  BQ: '599',
  BR: '55',
  BS: '+1-242',
  BT: '975',
  BV: '',
  BW: '267',
  BY: '375',
  BZ: '501',
  CA: '1',
  CC: '61',
  CD: '243',
  CF: '236',
  CG: '242',
  CH: '41',
  CI: '225',
  CK: '682',
  CL: '56',
  CM: '237',
  CN: '86',
  CO: '57',
  CR: '506',
  CU: '53',
  CV: '238',
  CW: '599',
  CX: '61',
  CY: '357',
  CZ: '420',
  DE: '49',
  DJ: '253',
  DK: '45',
  DM: '+1-767',
  DO: '+1-809 and 1-829',
  DZ: '213',
  EC: '593',
  EE: '372',
  EG: '20',
  EH: '212',
  ER: '291',
  ES: '34',
  ET: '251',
  FI: '358',
  FJ: '679',
  FK: '500',
  FM: '691',
  FO: '298',
  FR: '33',
  GA: '241',
  GB: '44',
  GD: '+1-473',
  GE: '995',
  GF: '594',
  GG: '+44-1481',
  GH: '233',
  GI: '350',
  GL: '299',
  GM: '220',
  GN: '224',
  GP: '590',
  GQ: '240',
  GR: '30',
  GS: '',
  GT: '502',
  GU: '+1-671',
  GW: '245',
  GY: '592',
  HK: '852',
  HM: ' ',
  HN: '504',
  HR: '385',
  HT: '509',
  HU: '36',
  ID: '62',
  IE: '353',
  IL: '972',
  IM: '+44-1624',
  IN: '91',
  IO: '246',
  IQ: '964',
  IR: '98',
  IS: '354',
  IT: '39',
  JE: '+44-1534',
  JM: '+1-876',
  JO: '962',
  JP: '81',
  KE: '254',
  KG: '996',
  KH: '855',
  KI: '686',
  KM: '269',
  KN: '+1-869',
  KP: '850',
  KR: '82',
  KW: '965',
  KY: '+1-345',
  KZ: '7',
  LA: '856',
  LB: '961',
  LC: '+1-758',
  LI: '423',
  LK: '94',
  LR: '231',
  LS: '266',
  LT: '370',
  LU: '352',
  LV: '371',
  LY: '218',
  MA: '212',
  MC: '377',
  MD: '373',
  ME: '382',
  MF: '590',
  MG: '261',
  MH: '692',
  MK: '389',
  ML: '223',
  MM: '95',
  MN: '976',
  MO: '853',
  MP: '+1-670',
  MQ: '596',
  MR: '222',
  MS: '+1-664',
  MT: '356',
  MU: '230',
  MV: '960',
  MW: '265',
  MX: '52',
  MY: '60',
  MZ: '258',
  NA: '264',
  NC: '687',
  NE: '227',
  NF: '672',
  NG: '234',
  NI: '505',
  NL: '31',
  NO: '47',
  NP: '977',
  NR: '674',
  NU: '683',
  NZ: '64',
  OM: '968',
  PA: '507',
  PE: '51',
  PF: '689',
  PG: '675',
  PH: '63',
  PK: '92',
  PL: '48',
  PM: '508',
  PN: '870',
  PR: '+1-787 and 1-939',
  PS: '970',
  PT: '351',
  PW: '680',
  PY: '595',
  QA: '974',
  RE: '262',
  RO: '40',
  RS: '381',
  RU: '7',
  RW: '250',
  SA: '966',
  SB: '677',
  SC: '248',
  SD: '249',
  SE: '46',
  SG: '65',
  SH: '290',
  SI: '386',
  SJ: '47',
  SK: '421',
  SL: '232',
  SM: '378',
  SN: '221',
  SO: '252',
  SR: '597',
  SS: '211',
  ST: '239',
  SV: '503',
  SX: '599',
  SY: '963',
  SZ: '268',
  TC: '+1-649',
  TD: '235',
  TF: '',
  TG: '228',
  TH: '66',
  TJ: '992',
  TK: '690',
  TL: '670',
  TM: '993',
  TN: '216',
  TO: '676',
  TR: '90',
  TT: '+1-868',
  TV: '688',
  TW: '886',
  TZ: '255',
  UA: '380',
  UG: '256',
  UM: '1',
  US: '1',
  UY: '598',
  UZ: '998',
  VA: '379',
  VC: '+1-784',
  VE: '58',
  VG: '+1-284',
  VI: '+1-340',
  VN: '84',
  VU: '678',
  WF: '681',
  WS: '685',
  XK: '383',
  YE: '967',
  YT: '262',
  ZA: '27',
  ZM: '260',
  ZW: '263',
}

const COUNTRY_NAME_FALLBACKS = {
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Antigua and Barbuda',
  AI: 'Anguilla',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AQ: 'Antarctica',
  AR: 'Argentina',
  AS: 'American Samoa',
  AT: 'Austria',
  AU: 'Australia',
  AW: 'Aruba',
  AX: 'Aland Islands',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'Saint Barthelemy',
  BM: 'Bermuda',
  BN: 'Brunei',
  BO: 'Bolivia',
  BQ: 'Bonaire, Saint Eustatius and Saba',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BV: 'Bouvet Island',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CC: 'Cocos Islands',
  CD: 'Democratic Republic of the Congo',
  CF: 'Central African Republic',
  CG: 'Republic of the Congo',
  CH: 'Switzerland',
  CI: 'Ivory Coast',
  CK: 'Cook Islands',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cape Verde',
  CW: 'Curacao',
  CX: 'Christmas Island',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DE: 'Germany',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  EH: 'Western Sahara',
  ER: 'Eritrea',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FK: 'Falkland Islands',
  FM: 'Micronesia',
  FO: 'Faroe Islands',
  FR: 'France',
  GA: 'Gabon',
  GB: 'United Kingdom',
  GD: 'Grenada',
  GE: 'Georgia',
  GF: 'French Guiana',
  GG: 'Guernsey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Greenland',
  GM: 'Gambia',
  GN: 'Guinea',
  GP: 'Guadeloupe',
  GQ: 'Equatorial Guinea',
  GR: 'Greece',
  GS: 'South Georgia and the South Sandwich Islands',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HM: 'Heard Island and McDonald Islands',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IM: 'Isle of Man',
  IN: 'India',
  IO: 'British Indian Ocean Territory',
  IQ: 'Iraq',
  IR: 'Iran',
  IS: 'Iceland',
  IT: 'Italy',
  JE: 'Jersey',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KI: 'Kiribati',
  KM: 'Comoros',
  KN: 'Saint Kitts and Nevis',
  KP: 'North Korea',
  KR: 'South Korea',
  KW: 'Kuwait',
  KY: 'Cayman Islands',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libya',
  MA: 'Morocco',
  MC: 'Monaco',
  MD: 'Moldova',
  ME: 'Montenegro',
  MF: 'Saint Martin',
  MG: 'Madagascar',
  MH: 'Marshall Islands',
  MK: 'North Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'Macao',
  MP: 'Northern Mariana Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NC: 'New Caledonia',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PM: 'Saint Pierre and Miquelon',
  PN: 'Pitcairn',
  PR: 'Puerto Rico',
  PS: 'Palestine',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RE: 'Reunion',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SB: 'Solomon Islands',
  SC: 'Seychelles',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SH: 'Saint Helena',
  SI: 'Slovenia',
  SJ: 'Svalbard and Jan Mayen',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  SS: 'South Sudan',
  ST: 'Sao Tome and Principe',
  SV: 'El Salvador',
  SX: 'Sint Maarten',
  SY: 'Syria',
  SZ: 'Eswatini',
  TC: 'Turks and Caicos Islands',
  TD: 'Chad',
  TF: 'French Southern Territories',
  TG: 'Togo',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TK: 'Tokelau',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TO: 'Tonga',
  TR: 'Turkey',
  TT: 'Trinidad and Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  UM: 'United States Minor Outlying Islands',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VA: 'Vatican City',
  VC: 'Saint Vincent and the Grenadines',
  VE: 'Venezuela',
  VG: 'British Virgin Islands',
  VI: 'U.S. Virgin Islands',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WF: 'Wallis and Futuna',
  WS: 'Samoa',
  XK: 'Kosovo',
  YE: 'Yemen',
  YT: 'Mayotte',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
}

const NAME_OVERRIDES = {
  AE: { nameAr: 'الإمارات العربية المتحدة' },
  AX: { nameAr: 'جزر آلاند' },
  BH: { nameAr: 'البحرين' },
  CD: { nameAr: 'جمهورية الكونغو الديمقراطية' },
  CG: { nameAr: 'جمهورية الكونغو' },
  CI: { nameAr: 'ساحل العاج' },
  CZ: { nameAr: 'التشيك' },
  EG: { nameAr: 'مصر' },
  GB: { nameAr: 'المملكة المتحدة' },
  IQ: { nameAr: 'العراق' },
  JO: { nameAr: 'الأردن' },
  KM: { nameAr: 'جزر القمر' },
  KR: { nameAr: 'كوريا الجنوبية' },
  KW: { nameAr: 'الكويت' },
  LB: { nameAr: 'لبنان' },
  LY: { nameAr: 'ليبيا' },
  MA: { nameAr: 'المغرب' },
  MK: { nameAr: 'مقدونيا الشمالية' },
  OM: { nameAr: 'عمان' },
  PS: { nameEn: 'Palestine', nameAr: 'فلسطين' },
  QA: { nameAr: 'قطر' },
  SA: { nameAr: 'السعودية' },
  SS: { nameAr: 'جنوب السودان' },
  SY: { nameAr: 'سوريا' },
  TL: { nameAr: 'تيمور الشرقية' },
  TN: { nameAr: 'تونس' },
  TR: { nameAr: 'تركيا' },
  TW: { nameAr: 'تايوان' },
  US: { nameAr: 'الولايات المتحدة' },
  YE: { nameAr: 'اليمن' },
}

const PHONE_RULES = {
  AE: { minLen: 9, maxLen: 9 },
  AR: { minLen: 10, maxLen: 10 },
  AT: { minLen: 10, maxLen: 13 },
  AU: { minLen: 9, maxLen: 9 },
  BD: { minLen: 10, maxLen: 10 },
  BE: { minLen: 9, maxLen: 9 },
  BH: { minLen: 8, maxLen: 8 },
  BR: { minLen: 10, maxLen: 11 },
  CA: { minLen: 10, maxLen: 10 },
  CD: { minLen: 9, maxLen: 9 },
  CG: { minLen: 9, maxLen: 9 },
  CH: { minLen: 9, maxLen: 9 },
  CN: { minLen: 11, maxLen: 11 },
  CZ: { minLen: 9, maxLen: 9 },
  DE: { minLen: 10, maxLen: 11 },
  DJ: { minLen: 8, maxLen: 8 },
  DK: { minLen: 8, maxLen: 8 },
  DZ: { minLen: 9, maxLen: 9 },
  EG: { minLen: 10, maxLen: 11 },
  ES: { minLen: 9, maxLen: 9 },
  ET: { minLen: 9, maxLen: 9 },
  FI: { minLen: 5, maxLen: 12 },
  FR: { minLen: 9, maxLen: 9 },
  GB: { minLen: 10, maxLen: 10 },
  GR: { minLen: 10, maxLen: 10 },
  HU: { minLen: 9, maxLen: 9 },
  ID: { minLen: 9, maxLen: 12 },
  IL: { minLen: 9, maxLen: 9 },
  IN: { minLen: 10, maxLen: 10 },
  IQ: { minLen: 10, maxLen: 10 },
  IR: { minLen: 10, maxLen: 10 },
  IT: { minLen: 9, maxLen: 10 },
  JO: { minLen: 9, maxLen: 9 },
  JP: { minLen: 10, maxLen: 10 },
  KE: { minLen: 9, maxLen: 9 },
  KM: { minLen: 7, maxLen: 7 },
  KR: { minLen: 9, maxLen: 11 },
  KW: { minLen: 8, maxLen: 8 },
  LB: { minLen: 7, maxLen: 8 },
  LY: { minLen: 9, maxLen: 9 },
  MA: { minLen: 9, maxLen: 9 },
  MR: { minLen: 8, maxLen: 8 },
  MX: { minLen: 10, maxLen: 10 },
  MY: { minLen: 9, maxLen: 10 },
  NG: { minLen: 10, maxLen: 10 },
  NL: { minLen: 9, maxLen: 9 },
  NO: { minLen: 8, maxLen: 8 },
  NZ: { minLen: 8, maxLen: 10 },
  OM: { minLen: 8, maxLen: 8 },
  PH: { minLen: 10, maxLen: 10 },
  PK: { minLen: 10, maxLen: 10 },
  PL: { minLen: 9, maxLen: 9 },
  PS: { minLen: 9, maxLen: 9 },
  PT: { minLen: 9, maxLen: 9 },
  QA: { minLen: 8, maxLen: 8 },
  RU: { minLen: 10, maxLen: 10 },
  SA: { minLen: 9, maxLen: 9 },
  SD: { minLen: 9, maxLen: 9 },
  SE: { minLen: 7, maxLen: 9 },
  SG: { minLen: 8, maxLen: 8 },
  SO: { minLen: 7, maxLen: 9 },
  TH: { minLen: 9, maxLen: 9 },
  TN: { minLen: 8, maxLen: 8 },
  TR: { minLen: 10, maxLen: 10 },
  UA: { minLen: 9, maxLen: 9 },
  US: { minLen: 10, maxLen: 10 },
  VN: { minLen: 9, maxLen: 9 },
  YE: { minLen: 9, maxLen: 9 },
  ZA: { minLen: 9, maxLen: 9 },
}

const PRIORITY_ISO2 = [
  'EG', 'SA', 'AE', 'KW', 'QA', 'BH', 'OM', 'JO', 'LB', 'SY',
  'IQ', 'PS', 'MA', 'DZ', 'TN', 'LY', 'SD', 'SO', 'DJ', 'KM',
  'MR', 'YE', 'CD', 'CG'
]

const DEFAULT_PHONE_RULE = { minLen: 4, maxLen: 15 }

const buildFlagEmoji = (iso2) =>
  String(iso2 || '')
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)))

const normalizeDialCode = (raw) => {
  const value = String(raw || '').trim()
  if (!value) return ''
  const match = value.match(/\+?[\d-]+/)
  if (!match) return ''
  const digits = match[0].replace(/[^0-9]/g, '')
  return digits ? `+${digits}` : ''
}

const displayNamesEn = typeof Intl !== 'undefined' && typeof Intl.DisplayNames === 'function'
  ? new Intl.DisplayNames(['en'], { type: 'region' })
  : null

const displayNamesAr = typeof Intl !== 'undefined' && typeof Intl.DisplayNames === 'function'
  ? new Intl.DisplayNames(['ar'], { type: 'region' })
  : null

const getCountryNameEn = (iso2) => {
  const override = NAME_OVERRIDES[iso2]?.nameEn
  if (override) return override
  return displayNamesEn?.of(iso2) || COUNTRY_NAME_FALLBACKS[iso2] || iso2
}

const getCountryNameAr = (iso2) => {
  const override = NAME_OVERRIDES[iso2]?.nameAr
  if (override) return override
  return displayNamesAr?.of(iso2) || getCountryNameEn(iso2)
}

export const COUNTRY_CODES = Object.entries(COUNTRY_DIAL_CODE_MAP)
  .map(([iso2, rawDialCode]) => {
    const dialCode = normalizeDialCode(rawDialCode)
    if (!dialCode) return null

    const rule = PHONE_RULES[iso2] || DEFAULT_PHONE_RULE
    return {
      iso2,
      nameEn: getCountryNameEn(iso2),
      nameAr: getCountryNameAr(iso2),
      dialCode,
      flag: buildFlagEmoji(iso2),
      minLen: rule.minLen,
      maxLen: rule.maxLen,
    }
  })
  .filter(Boolean)
  .sort((a, b) => {
    const aPriority = PRIORITY_ISO2.indexOf(a.iso2)
    const bPriority = PRIORITY_ISO2.indexOf(b.iso2)

    if (aPriority !== -1 || bPriority !== -1) {
      if (aPriority === -1) return 1
      if (bPriority === -1) return -1
      return aPriority - bPriority
    }

    return a.nameEn.localeCompare(b.nameEn)
  })

export const validatePhoneNumber = (code, number) => {
  const sanitizePhone = (input) => String(input || '').replace(/[^0-9]/g, '')
  const cleanNumber = sanitizePhone(number)

  if (!cleanNumber) return { isValid: false, message: 'Required' }

  const rule = COUNTRY_CODES.find((c) => c.dialCode === code)
  if (!rule) return { isValid: true, message: '' }

  if (code === '+20') {
    const isLeadingZeroFormat = cleanNumber.startsWith('0')
    const expectedLength = isLeadingZeroFormat ? 11 : 10

    if (cleanNumber.length !== expectedLength) {
      return {
        isValid: false,
        message: isLeadingZeroFormat
          ? 'Egypt mobile numbers starting with 0 must be exactly 11 digits'
          : 'Egypt mobile numbers without 0 must be exactly 10 digits',
        messageAr: isLeadingZeroFormat
          ? 'رقم الموبايل المصري الذي يبدأ بـ 0 يجب أن يكون 11 رقمًا بالضبط'
          : 'رقم الموبايل المصري بدون 0 في البداية يجب أن يكون 10 أرقام بالضبط',
      }
    }

    return { isValid: true, message: '' }
  }

  if (cleanNumber.length < rule.minLen || cleanNumber.length > rule.maxLen) {
    return {
      isValid: false,
      message: `Must be ${rule.minLen === rule.maxLen ? rule.minLen : `${rule.minLen}-${rule.maxLen}`} digits`,
      messageAr: `يجب أن يكون ${rule.minLen === rule.maxLen ? rule.minLen : `${rule.minLen}-${rule.maxLen}`} رقمًا`,
    }
  }

  return { isValid: true, message: '' }
}

export const usePhoneValidation = () => {
  const sanitizePhone = (input) => String(input || '').replace(/[^0-9]/g, '')

  const getCountryRule = (code) => COUNTRY_CODES.find((c) => c.dialCode === code)

  const validatePhone = (code, number) => validatePhoneNumber(code, number)

  return {
    COUNTRY_CODES,
    sanitizePhone,
    validatePhone,
    getCountryRule,
  }
}
